sudo: true
language: node_js
node_js:
  - "7"
os:
- linux
- osx
osx_image: xcode8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libcap-dev
cache: yarn
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source ci/linux-before-install.sh; fi
install:
  - yarn global add node-gyp
  - yarn
script:
  - make lint
  - make build
notifications:
  email: false
